### ISSUE TITLE
feature-request: add ability to override email address for resend

### ISSUE THREAD

**Issue by MikeCraig418** [oakeddev/statamic-resend-form-submissions#2]
Use Case:

- Sometimes a submission will come to the wrong form. In this case it would nice to manually specify an email and override the original admin recipient.

Possible UI/UX:

- [x] User selects all submissions they want to resend
- [x] The user presses the Resend button (or perhaps clicks a dropdown to choose "Resend to Manual Email"
- [x] A modal window opens where the user can see the email address of the original email
- [x] The user can override or specify a new email address
- [x] The user sends and the recipient receives the email

---

Thanks again :)

**Comment by oakeddev** [comment]
@mi-ke-dev You are lucky: this feature was already on the roadmap. :) I have just released a new 1.1.0 version with this feature.
